export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  dashboard: "/dashboard",
  products: "/dashboard/products",
  categories: "/dashboard/categories",
  userDashboard: "/user",
  userSettings: "/user/dashboard/settings",
  userPaymentMethod: "/user/dashboard/payment-method",
  userAddress: "/user/dashboard/address",
  userOrders: "/user/dashboard/orders",
  userProducts: "/user/dashboard/products",
  userCategories: "/user/dashboard/categories",

  // "/": "Home",
  // "/login": "Login",
  // "/register": "Register",
  // "/dashboard": "Dashboard",
  // "/dashboard/products": "Products",
  // "/dashboard/categories": "Categories",
  // "/dashboard/orders": "Orders",
  // "/dashboard/customers": "Customers",
  // "/dashboard/settings": "Settings",
  // "/dashboard/payment-method": "Payment Method",
  // "/dashboard/address": "Address",
  // "/user/dashboard": "User Dashboard",
  // "/user/dashboard/settings": "User Settings",
  // "/user/dashboard/payment-method": "User Payment Method",
  // "/user/dashboard/address": "User Address",
  // "/user/dashboard/orders": "User Orders",
  // "/user/dashboard/products": "User Products",
  // "/user/dashboard/categories": "User Categories",
  // "/user/dashboard/orders": "User Orders",
};
